wandb: ERROR Project g4nlp/static-dataset does not contain artifact: "static-graphs"
Traceback (most recent call last):
  File "C:\Users\liamb\Documents\graph4stackoverflow\venv\lib\site-packages\wandb\apis\normalize.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\liamb\Documents\graph4stackoverflow\venv\lib\site-packages\wandb\apis\public.py", line 955, in artifact
    artifact = Artifact(self.client, entity, project, artifact_name)
  File "C:\Users\liamb\Documents\graph4stackoverflow\venv\lib\site-packages\wandb\apis\public.py", line 4368, in __init__
    self._load()
  File "C:\Users\liamb\Documents\graph4stackoverflow\venv\lib\site-packages\wandb\apis\public.py", line 5097, in _load
    raise ValueError(
ValueError: Project g4nlp/static-dataset does not contain artifact: "static-graphs"
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\liamb\Documents\graph4stackoverflow\embeddings\hetero_GAT.py", line 181, in <module>
    start_wandb_for_training(wandb_project_name)
  File "C:\Users\liamb\Documents\graph4stackoverflow\embeddings\hetero_GAT.py", line 159, in start_wandb_for_training
    wandb.use_artifact("static-dataset/static-graphs")
  File "C:\Users\liamb\Documents\graph4stackoverflow\venv\lib\site-packages\wandb\sdk\wandb_run.py", line 334, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\liamb\Documents\graph4stackoverflow\venv\lib\site-packages\wandb\sdk\wandb_run.py", line 2635, in use_artifact
    artifact = public_api.artifact(type=type, name=name)
  File "C:\Users\liamb\Documents\graph4stackoverflow\venv\lib\site-packages\wandb\apis\normalize.py", line 64, in wrapper
    raise CommError(message, err).with_traceback(sys.exc_info()[2])
  File "C:\Users\liamb\Documents\graph4stackoverflow\venv\lib\site-packages\wandb\apis\normalize.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\liamb\Documents\graph4stackoverflow\venv\lib\site-packages\wandb\apis\public.py", line 955, in artifact
    artifact = Artifact(self.client, entity, project, artifact_name)
  File "C:\Users\liamb\Documents\graph4stackoverflow\venv\lib\site-packages\wandb\apis\public.py", line 4368, in __init__
    self._load()
  File "C:\Users\liamb\Documents\graph4stackoverflow\venv\lib\site-packages\wandb\apis\public.py", line 5097, in _load
    raise ValueError(
wandb.errors.CommError: Project g4nlp/static-dataset does not contain artifact: "static-graphs"